apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: platpilot
spec:
  containers:
  - name: my-container
    image: busybox
    command:
      - /bin/sh
      - -c
      - while true; do echo \"hello world\"; sleep 1; done